#!/usr/bin/env quick-exec
(println "Hello World!")
(println "Press ENTER") (read-line)
(println "Hello Again!")
(println "Hello Again!")
(println "Hello Again!")
(println "Hello Again!")
(println "Press ENTER") (read-line)
;(leiningen.core.main/exit 2)
(throw (ex-info "test" {:a 1}))
